-
  name: "samtools"
  type: "autotools"
  versions: [1.9, 1.8, 1.7, 1.6, 1.5, 1.4.1, 1.4, 1.3]
  url: "https://github.com/samtools/samtools/releases/download/{version}/samtools-{version}.tar.bz2"
  builddep: "gcc make libc-dev ncurses-dev bzip2-dev zlib-dev curl-dev curl xz-dev"
  runtimedep: "ncurses libbz2 zlib libcurl xz-libs"
-
  name: "samtools"
  type: "make"
  versions: [0.1.19, 0.1.18, 1.0, 1.1, 1.2]
  url: "https://downloads.sourceforge.net/project/samtools/samtools/{version}/samtools-{version}.tar.bz2"
  builddep: "gcc make libc-dev ncurses-dev bzip2-dev zlib-dev curl-dev curl"
  runtimedep: "ncurses libbz2 zlib libcurl"
  artifacts:
    -
      file: "samtools"
      dest: "/usr/bin"