-
  name: "bedtools"
  type: "make"
  versions: ["2.27.1", "2.27.0", "2.26.0", "2.25.0", "2.24.0", "2.23.0", "2.22.1", "2.22.0", "2.21.0"]
  url: "https://github.com/arq5x/bedtools2/releases/download/v{version}/bedtools-{version}.tar.gz"
  archivename: "bedtools2"
  builddep: "gcc g++ make libc-dev zlib-dev bash python2"
  runtimedep: "zlib libstdc++"
  artifacts:
    -
      file: "bin/*"
      dest: "/usr/bin"
